permalink: /blog/:title

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Rafael Garbin
description: Eu atuo como desenvolvedor de software, ajudando minha equipe a desenvolver produtos incriveis para nossos clientes. Eu sou um entusiasta de tecnologia em geral que adora ajudar os outros a aprender, inovar e eliminar desperdício. Um Unix maníaco assumido, estou sempre à procura de novos desafios focando em entregas com qualidade que agrege valor para os clientes.
keywords: Analista, Desenvolvedor, Software, Portifolio, Blog, Garbin
author :
  name : Rafael Garbin
  email : rgarbin@gmail.com
  github : https://github.com/rgarbin
  twitter: https://twitter.com/rgarbin
  facebook: http://www.facebook.com/rgarbin
  linkdin: http://br.linkedin.com/in/rgarbin

production_url : http://rgarbin.github.io
